'use client';

import { createContext, useContext, useState, useEffect } from 'react';

// Dictionnaire de traduction
const translations = {
  fr: {
    // Navigation
    home: 'Accueil',
    products: 'Produits',
    categories: 'Catégories',
    cart: 'Panier',
    account: 'Compte',
    dashboard: 'Tableau de bord',
    orders: 'Commandes',
    sellers: 'Vendeurs',
    customers: 'Clients',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: 'Inscription',
    contact: 'Contact',
    help: 'Aide',
    schoolLists: 'Listes Scolaires',
    becomeSeller: 'Devenir Vendeur',
    favorites: 'Favoris',
    wishlist: 'Liste de souhaits',
    delivery: 'Livraison',
    myOrders: 'Mes commandes',
    myAccount: 'Mon compte',
    profile: 'Profil',
    myStore: 'Mon magasin',
    administration: 'Administration',
    management: 'Gestion',
    sellerSpace: 'Espace vendeur',
    
    // Actions
    search: 'Rechercher',
    searchPlaceholder: 'Rechercher des produits...',
    filter: 'Filtrer',
    sort: 'Trier',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    subscribe: 'S\'inscrire',
    
    // Produits
    price: 'Prix',
    stock: 'Stock',
    description: 'Description',
    addToCart: 'Ajouter au panier',
    outOfStock: 'Rupture de stock',
    
    // Commandes
    orderNumber: 'Numéro de commande',
    orderDate: 'Date de commande',
    orderStatus: 'Statut de la commande',
    orderTotal: 'Total de la commande',
    
    // Statuts
    pending: 'En attente',
    processing: 'En cours',
    shipped: 'Expédié',
    delivered: 'Livré',
    cancelled: 'Annulé',
    
    // Messages
    welcome: 'Bienvenue',
    notifications: 'Notifications',
    noItems: 'Aucun élément trouvé',
    newOrderReceived: 'Nouvelle commande reçue',
    newSupportMessage: 'Nouveau message de support',
    lowStockFor: 'Stock faible pour "{product}"',
    minutesAgo: 'Il y a {minutes} minutes',
    hoursAgo: 'Il y a {hours} heure(s)',
    viewAllNotifications: 'Voir toutes les notifications',
    
    // Notifications
    noNotifications: 'Aucune notification',
    
    // Thème
    darkMode: 'Mode sombre',
    lightMode: 'Mode clair',
    
    // Langue
    language: 'Langue',
    french: 'Français',
    english: 'Anglais',
    selectLanguage: 'Sélectionner la langue',
    
    // Footer
    aboutUs: 'À propos',
    aboutUsText: 'Votre marketplace en ligne pour tous vos besoins d\'achat et de vente.',
    quickLinks: 'Liens rapides',
    about: 'À propos',
    faq: 'FAQ',
    termsOfUse: 'Conditions d\'utilisation',
    privacyPolicy: 'Politique de confidentialité',
    newsletter: 'Newsletter',
    newsletterText: 'Inscrivez-vous pour recevoir nos dernières offres et promotions.',
    emailPlaceholder: 'Votre adresse e-mail',
    allRightsReserved: 'Tous droits réservés.',
    
    // Become Seller Page
    becomeSellerTitle: 'VOUS VOULEZ VENDRE?',
    becomeSellerSubtitle: 'Devenez vendeur sur Penventory!',
    becomeSellerDescription: 'Rejoignez notre marketplace et atteignez des milliers de clients potentiels. Vendez vos produits facilement et développez votre activité avec nous.',
    becomeSellerButton: 'DEVENIR UN VENDEUR',
    sellerStepsTitle: 'VRAIMENT FACILE À CONFIGURER ET À PERSONNALISER',
    sellerStep1Title: 'Créer un compte',
    sellerStep1Description: 'Créez un compte vendeur sur PInventory pour commencer à vendre vos produits.',
    sellerStep2Title: 'Créez votre profil',
    sellerStep2Description: 'Complétez votre profil vendeur avec toutes les informations nécessaires.',
    sellerStep3Title: 'Ajoutez vos coordonnées',
    sellerStep3Description: 'Ajoutez vos coordonnées bancaires et fiscales pour recevoir vos paiements.',
    sellerStep4Title: 'Ajoutez votre liste de produits',
    sellerStep4Description: 'Créez votre catalogue de produits avec des descriptions détaillées et des images de qualité.',
    sellerStep5Title: 'Vendez vos produits et gagnez des points',
    sellerStep5Description: 'Commencez à vendre et gagnez des points de fidélité pour débloquer des avantages exclusifs.',
    sellerBenefitsTitle: 'POURQUOI VENDRE SUR PENVENTORY?',
    benefit1Title: 'Acheteurs importants',
    benefit1Description: 'Accédez à une large base de clients, avec de nombreux acheteurs réguliers.',
    benefit2Title: 'Paiements rapides',
    benefit2Description: 'Une fois les produits livrés aux clients, vous pouvez demander votre paiement immédiatement.',
    benefit3Title: 'Gagner des badges',
    benefit3Description: 'Gagnez des badges de performance qui vous démarquent comme un vendeur professionnel.',
    benefit4Title: 'Personnaliser le profil',
    benefit4Description: 'Personnalisez votre profil avec des informations comme le logo, l\'emplacement et les politiques de retour.',
    benefit5Title: 'Ajouter des médias',
    benefit5Description: 'Intégrez des vidéos YouTube pour rendre votre boutique plus authentique et vous démarquer.',
    callToActionTitle: 'PRÊT À COMMENCER VOTRE AVENTURE DE VENTE?',
    callToActionDescription: 'Rejoignez des milliers de vendeurs qui ont déjà augmenté leurs revenus en vendant sur Penventory.',
    signUpAsSeller: 'INSCRIVEZ-VOUS EN TANT QUE VENDEUR',
    faqTitle: 'QUESTIONS FRÉQUENTES',
    faq1Question: 'Comment puis-je m\'inscrire en tant que vendeur ?',
    faq1Answer: 'Pour vous inscrire en tant que vendeur, cliquez sur le bouton "Devenir vendeur" en haut de cette page, puis suivez les étapes d\'inscription. Vous devrez fournir des informations sur votre entreprise, vos coordonnées bancaires et fiscales.',
    faq2Question: 'Quels sont les frais pour vendre sur Penventory ?',
    faq2Answer: 'Penventory prélève une commission de 5% sur chaque vente réalisée sur la plateforme. Il n\'y a pas de frais d\'inscription ou d\'abonnement mensuel.',
    faq3Question: 'Comment sont gérés les paiements ?',
    faq3Answer: 'Les paiements sont sécurisés et traités par notre système. Une fois qu\'une commande est livrée et confirmée par le client, vous pouvez demander un virement sur votre compte bancaire. Les paiements sont généralement traités sous 3 jours ouvrables.',
    faq4Question: 'Comment gérer mes produits et commandes ?',
    faq4Answer: 'Une fois inscrit, vous aurez accès à un tableau de bord vendeur où vous pourrez ajouter, modifier et supprimer des produits, ainsi que gérer vos commandes, suivre vos ventes et communiquer avec les clients.',
    faq5Question: 'Puis-je vendre n\'importe quel type de produit ?',
    faq5Answer: 'Vous pouvez vendre la plupart des produits légaux, mais certaines catégories sont restreintes ou interdites. Consultez nos conditions d\'utilisation pour plus de détails sur les produits autorisés et interdits.',
    helpSectionTitle: 'Vous êtes coincé? Posez des questions',
    helpSectionDescription: 'Si vous avez des questions sur le processus de vente, n\'hésitez pas à nous contacter. Nous sommes là pour vous aider!',
    helpCenter: 'Centre d\'aide',
    liveChat: 'Chat en direct',
    
    // Help Page
    helpPageTitle: 'Centre d\'assistance',
    helpPageSubtitle: 'Comment pouvons-nous vous aider aujourd\'hui?',
    searchPlaceholder: 'Tapez des mots-clés comme « retour »',
    searchButton: 'Rechercher',
    helpCategory1Title: 'Passer une commande',
    helpCategory1Description: 'Tout ce que vous devez savoir pour passer une commande sur notre plateforme.',
    helpCategory2Title: 'Suivre votre colis',
    helpCategory2Description: 'Comment suivre vos commandes et connaître leur statut de livraison.',
    helpCategory3Title: 'Méthode de paiement',
    helpCategory3Description: 'Informations sur les différentes méthodes de paiement disponibles.',
    helpCategory4Title: 'Annuler des commandes',
    helpCategory4Description: 'Comment annuler une commande ou effectuer un retour.',
    helpCategory5Title: 'Gérer votre compte',
    helpCategory5Description: 'Tout sur la gestion de votre compte et vos informations personnelles.',
    needMoreHelp: 'Besoin de plus d\'aide ?',
    needMoreHelpDescription: 'Si vous ne trouvez pas la réponse à votre question, n\'hésitez pas à contacter notre équipe de support.',
    contactUs: 'Contactez-nous',
    
    // FAQ Orders
    faqOrder1Question: 'Comment passer une commande sur PInventory ?',
    faqOrder1Answer: 'Pour passer une commande sur PInventory, suivez ces étapes simples :\n      1. Parcourez notre catalogue et trouvez les produits qui vous intéressent\n      2. Ajoutez les produits à votre panier en cliquant sur le bouton "Ajouter au panier"\n      3. Accédez à votre panier en cliquant sur l\'icône du panier en haut à droite\n      4. Vérifiez votre commande et cliquez sur "Passer la commande"\n      5. Remplissez vos informations de livraison et de paiement\n      6. Confirmez votre commande',
    faqOrder2Question: 'Puis-je modifier ma commande après l\'avoir passée ?',
    faqOrder2Answer: 'Vous pouvez modifier votre commande uniquement si elle n\'a pas encore été traitée. Pour ce faire, accédez à votre compte, consultez vos commandes récentes et cliquez sur "Modifier" si cette option est disponible. Si votre commande a déjà été traitée, vous devrez contacter notre service client pour obtenir de l\'aide.',
    faqOrder3Question: 'Comment puis-je vérifier la disponibilité d\'un produit ?',
    faqOrder3Answer: 'La disponibilité d\'un produit est indiquée sur sa page produit. Si un produit est en stock, vous verrez la mention "En stock" et vous pourrez l\'ajouter à votre panier. Si un produit est épuisé, vous verrez la mention "Rupture de stock" et vous pourrez vous inscrire pour être notifié lorsqu\'il sera à nouveau disponible.',
    
    // FAQ Tracking
    faqTracking1Question: 'Comment suivre ma commande ?',
    faqTracking1Answer: 'Pour suivre votre commande, suivez ces étapes :\n      1. Connectez-vous à votre compte\n      2. Accédez à la section "Mes commandes"\n      3. Trouvez la commande que vous souhaitez suivre\n      4. Cliquez sur "Suivre ma commande"\n      \n      Vous pourrez voir le statut actuel de votre commande et l\'emplacement de votre colis si la livraison est en cours.',
    faqTracking2Question: 'Quels sont les différents statuts de livraison ?',
    faqTracking2Answer: 'Voici les différents statuts de livraison que vous pourriez voir :\n      - Commande reçue : Nous avons reçu votre commande\n      - En cours de traitement : Votre commande est en cours de préparation\n      - Expédiée : Votre commande a été remise au transporteur\n      - En transit : Votre commande est en route vers vous\n      - Livrée : Votre commande a été livrée à l\'adresse indiquée\n      - Retardée : Il y a un retard dans la livraison de votre commande',
    faqTracking3Question: 'Combien de temps faut-il pour livrer ma commande ?',
    faqTracking3Answer: 'Le délai de livraison dépend de votre emplacement et du mode de livraison choisi. En général, les délais de livraison sont les suivants :\n      - Livraison standard : 3-5 jours ouvrables\n      - Livraison express : 1-2 jours ouvrables\n      \n      Vous pouvez voir l\'estimation du délai de livraison lors du passage de votre commande.',
    
    // FAQ Payment
    faqPayment1Question: 'Quelles sont les méthodes de paiement acceptées ?',
    faqPayment1Answer: 'Nous acceptons plusieurs méthodes de paiement pour votre commodité :\n      - Cartes de crédit/débit (Visa, Mastercard)\n      - PayPal\n      - Virement bancaire\n      - Paiement à la livraison (pour certaines régions)',
    faqPayment2Question: 'Mes informations de paiement sont-elles sécurisées ?',
    faqPayment2Answer: 'Oui, toutes les informations de paiement sont sécurisées. Nous utilisons un cryptage SSL pour protéger vos données personnelles et financières. Nous ne stockons pas vos informations de carte de crédit sur nos serveurs.',
    faqPayment3Question: 'Quand mon compte sera-t-il débité ?',
    faqPayment3Answer: 'Votre compte sera débité au moment où vous passez votre commande. Si un produit n\'est pas disponible ou si votre commande est annulée pour une raison quelconque, vous serez remboursé intégralement.',
    
    // FAQ Returns
    faqReturns1Question: 'Comment annuler ma commande ?',
    faqReturns1Answer: 'Pour annuler votre commande, suivez ces étapes :\n      1. Connectez-vous à votre compte\n      2. Accédez à la section "Mes commandes"\n      3. Trouvez la commande que vous souhaitez annuler\n      4. Cliquez sur "Annuler la commande"\n      \n      Veuillez noter que vous ne pouvez annuler une commande que si elle n\'a pas encore été expédiée. Si votre commande a déjà été expédiée, vous devrez la retourner une fois reçue.',
    faqReturns2Question: 'Comment retourner un produit ?',
    faqReturns2Answer: 'Pour retourner un produit, suivez ces étapes :\n      1. Connectez-vous à votre compte\n      2. Accédez à la section "Mes commandes"\n      3. Trouvez la commande contenant le produit que vous souhaitez retourner\n      4. Cliquez sur "Retourner un article"\n      5. Suivez les instructions pour imprimer l\'\u00e9tiquette de retour\n      \n      Une fois que nous aurons reçu et vérifié le produit retourné, nous procéderons au remboursement.',
    
    // FAQ Account
    faqAccount1Question: 'Comment créer un compte ?',
    faqAccount1Answer: 'Pour créer un compte sur PInventory, suivez ces étapes :\n      1. Cliquez sur l\'icône de profil en haut à droite de la page\n      2. Sélectionnez "S\'inscrire"\n      3. Remplissez le formulaire avec vos informations personnelles\n      4. Créez un mot de passe sécurisé\n      5. Cliquez sur "Créer un compte"\n      \n      Vous recevrez un e-mail de confirmation pour activer votre compte.',
    faqAccount2Question: 'Comment modifier mes informations personnelles ?',
    faqAccount2Answer: 'Pour modifier vos informations personnelles, suivez ces étapes :\n      1. Connectez-vous à votre compte\n      2. Accédez à la section "Mon profil"\n      3. Cliquez sur "Modifier" à côté des informations que vous souhaitez mettre à jour\n      4. Effectuez vos modifications\n      5. Cliquez sur "Enregistrer"\n      \n      Vos informations seront mises à jour immédiatement.',
    faqAccount3Question: 'J\'ai oublié mon mot de passe, que dois-je faire ?',
    faqAccount3Answer: 'Si vous avez oublié votre mot de passe, suivez ces étapes :\n      1. Cliquez sur l\'icône de profil en haut à droite de la page\n      2. Sélectionnez "Se connecter"\n      3. Cliquez sur "Mot de passe oublié"\n      4. Entrez l\'adresse e-mail associée à votre compte\n      5. Cliquez sur "Réinitialiser le mot de passe"\n      \n      Vous recevrez un e-mail avec un lien pour réinitialiser votre mot de passe.',
    
    // Traductions pour le chat support
    chatSupportTitle: "Assistance par chat",
    chatWelcomeTitle: "Bienvenue",
    chatWelcomeDescription: "Comment pouvons-nous vous aider ?",
    contactInfoTitle: "Informations de contact",
    firstName: "Prénom",
    lastName: "Nom",
    email: "Email",
    validate: "Valider",
    chooseOption: "Merci de choisir l'une des options suivantes",
    back: "Retour",
    typingPlaceholder: "Tapez votre message...",
    cannotTypeNow: "Vous ne pouvez pas taper maintenant",
    
    // Catégories de support
    supportCategory1: "Passation de commande",
    supportCategory2: "Paramètres de compte",
    supportCategory3: "Paiement et bons d'achat",
    supportCategory4: "Autre demande générale",
    supportCategory5: "Demande liée à une commande",
    
    // Messages du chat
    chatWelcomeMessage: "Bonjour {firstName}, je suis l'assistant virtuel. Je suis là pour répondre à vos questions.",
    chatCategoryMessage: "Merci de choisir l'une des options suivantes concernant \"{categoryLabel}\"",
    chatNoPredefResponse: "Je n'ai pas de réponse prédéfinie pour cette question. Souhaitez-vous parler à un agent?",
    chatAgentSoon: "Merci pour votre message. Un agent va vous répondre dès que possible.",
    chatHelpWithElse: "Est-ce que je peux vous aider avec autre chose?",
    chatConnectAgent: "Nous allons vous mettre en relation avec un agent. Veuillez patienter quelques instants.",
    chatThanks: "Merci d'avoir utilisé notre service de chat. N'hésitez pas à revenir si vous avez d'autres questions!",
    chatClosed: "La conversation a été fermée",
    
    // Réponses rapides
    quickReplyYesAgent: "Oui, je veux parler à un agent",
    quickReplyNoThanks: "Non, merci",
    quickReplyNewConversation: "Nouvelle conversation",
    quickReplyAnotherQuestion: "Oui, j'ai une autre question",
    
    // Questions fréquentes du chat
    chatFaqOrder1: "Comment passer une commande ?",
    chatFaqOrder2: "Puis-je modifier ma commande après l'avoir passée ?",
    chatFaqAccount1: "Comment modifier mes informations personnelles ?",
    chatFaqAccount2: "Comment changer mon mot de passe ?",
    chatFaqPayment1: "Comment effectuer un paiement avec une carte bancaire ?",
    chatFaqPayment2: "Comment utiliser un bon d'achat ?",
    chatFaqPayment3: "Vérifier mon solde de crédit",
    chatFaqGeneral1: "Comment contacter le service client ?",
    chatFaqGeneral2: "Quels sont vos horaires d'ouverture ?",
    chatFaqOrderRelated1: "Quand ma commande sera-t-elle livrée ?",
    chatFaqOrderRelated2: "Comment suivre ma livraison ?",
    chatFaqOrderRelated3: "Puis-je modifier mon adresse de livraison ?",
    
    // Réponses prédéfinies
    predefinedResponseOrder1: "Pour passer une commande, suivez ces étapes:\n    1. Parcourez notre catalogue et ajoutez les produits souhaités à votre panier\n    2. Cliquez sur l'icône du panier pour voir votre sélection\n    3. Cliquez sur \"Passer la commande\"\n    4. Remplissez vos informations de livraison et de paiement\n    5. Confirmez votre commande",
    predefinedResponsePayment3Step1: "Pour vérifier votre solde de crédit vous pouvez:",
    predefinedResponsePayment3Step2: "1. Vous connecter sur votre compte",
    predefinedResponsePayment3Step3: "2. Cliquer sur \"compte\" puis crédit",
    predefinedResponsePayment3Step4: "OU",
    predefinedResponsePayment3Step5: "1. Vous connecter sur votre compte via web ou application",
    predefinedResponsePayment3Step6: "2. Vérifier le solde sous la section \"Crédit\"",
    predefinedResponseOrderRelated2Step1: "Pour suivre votre livraison:",
    predefinedResponseOrderRelated2Step2: "1. Connectez-vous à votre compte",
    predefinedResponseOrderRelated2Step3: "2. Accédez à \"Mes commandes\"",
    predefinedResponseOrderRelated2Step4: "3. Sélectionnez la commande concernée",
    predefinedResponseOrderRelated2Step5: "4. Cliquez sur \"Suivre ma livraison\"",
    
    // Page de contact
    contactPageTitle: "Contactez-nous",
    contactPageSubtitle: "Nous sommes là pour vous aider. Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.",
    contactInfoTitle: "Informations de contact",
    emailLabel: "Email",
    phoneLabel: "Téléphone",
    addressLabel: "Adresse",
    openingHoursTitle: "Heures d'ouverture",
    openingHoursContent: "Lundi - Vendredi: 9h00 - 18h00\nSamedi: 9h00 - 13h00\nDimanche: Fermé",
    sendMessageTitle: "Envoyez-nous un message",
    fullNameLabel: "Nom complet",
    subjectLabel: "Sujet",
    orderNumberLabel: "Numéro de commande (si applicable)",
    categoryLabel: "Catégorie",
    priorityLabel: "Priorité",
    messageLabel: "Message",
    sendingButton: "Envoi en cours...",
    sendButton: "Envoyer le message",
    thankYouTitle: "Merci pour votre message!",
    thankYouMessage: "Votre demande a été soumise avec succès. Notre équipe de support vous répondra dans les plus brefs délais.",
    referenceNumberLabel: "Numéro de référence:",
    keepReferenceMessage: "Veuillez conserver ce numéro de référence pour le suivi de votre demande.",
    submitAnotherRequest: "Soumettre une autre demande",
    faqTitle: "Questions fréquemment posées",
    trackOrderQuestion: "Comment suivre ma commande?",
    trackOrderAnswer: "Connectez-vous à votre compte, accédez à \"Mes commandes\" et cliquez sur \"Suivre\" à côté de votre commande.",
    returnPolicyQuestion: "Politique de retour",
    returnPolicyAnswer: "Vous pouvez retourner un produit dans les 14 jours suivant la réception si vous n'êtes pas satisfait.",
    paymentMethodsQuestion: "Méthodes de paiement",
    paymentMethodsAnswer: "Nous acceptons les cartes de crédit/débit, le paiement à la livraison et les virements bancaires.",
    
    // Catégories de support
    contactCategoryPayment: "Paiement",
    contactCategoryShipping: "Livraison",
    contactCategoryProduct: "Produit",
    contactCategoryAccount: "Compte",
    contactCategoryOther: "Autre",
    
    // Priorités de support
    contactPriorityLow: "Basse",
    contactPriorityMedium: "Moyenne",
    contactPriorityHigh: "Haute",
    contactPriorityUrgent: "Urgente",
    
    // Messages de toast
    contactSuccessMessage: "Votre demande a été soumise avec succès!",
    contactErrorAuth: "Veuillez vous connecter pour soumettre un ticket de support.",
    contactErrorGeneral: "Une erreur est survenue. Veuillez réessayer.",
    
    // Page d'accueil
    homeCategories: "Catégories de stylos",
    homeFeaturedProducts: "Produits en vedette",
    homeFeaturedProductsSubtitle: "Découvrez notre sélection de stylos de luxe",
    homeBrands: "Nos marques partenaires",
    homeBrandsSubtitle: "Les plus grandes marques nous font confiance",
    homeViewAll: "Voir tout",
    homeAddToCart: "Ajouter au panier",
    homeReviews: "avis",
    homeLowStock: "Plus que {stock} en stock",
    homeOutOfStock: "Rupture de stock",
    homeAdvantage1Title: "Qualité premium",
    homeAdvantage1Subtitle: "Sélection rigoureuse des produits",
    homeAdvantage2Title: "Garantie authentique",
    homeAdvantage2Subtitle: "Produits 100% authentiques",
    homeAdvantage3Title: "Livraison rapide",
    homeAdvantage3Subtitle: "Expédition sous 24h",
    
    // Erreurs API
    errorCategories: "Erreur lors de la récupération des catégories",
    errorProducts: "Erreur lors de la récupération des produits en vedette",
    errorBrands: "Erreur lors de la récupération des marques",
    
    // Catégories par défaut
    defaultCategory1: "Stylos de luxe",
    defaultCategory2: "Stylos à plume",
    defaultCategory3: "Stylos à bille",
    defaultCategory4: "Stylos rollers",
    defaultCategory5: "Crayons & Porte-mines",
    defaultCategory6: "Accessoires d'écriture",
    
    // Page Livraison
    deliveryTitle: "Tout savoir sur nos solutions de livraison",
    deliverySubtitle: "Nous proposons différentes options de livraison pour répondre à vos besoins. Découvrez nos tarifs et délais de livraison.",
    deliveryInfoTitle: "Nos services de livraison",
    deliveryInfoDescription: "Nous travaillons avec les meilleurs transporteurs pour vous offrir un service de qualité. Voici les différentes options disponibles :",
    standardDelivery: "Livraison standard",
    standardDeliveryDescription: "Livraison économique pour vos commandes habituelles, avec suivi de colis.",
    expressDelivery: "Livraison express",
    expressDeliveryDescription: "Livraison rapide pour vos commandes urgentes, avec garantie de délai.",
    deliveryTime: "Délais de livraison",
    deliveryTimeDescription: "Nos délais varient selon votre localisation et le type de livraison choisi.",
    secureDelivery: "Livraison sécurisée",
    secureDeliveryDescription: "Tous nos colis sont emballés avec soin et assurés pendant le transport.",
    deliveryRatesTitle: "Tarifs de livraison",
    deliveryZone: "Zone de livraison",
    standardRate: "Tarif standard",
    expressRate: "Tarif express",
    greaterTunis: "Grand Tunis",
    northTunisia: "Nord de la Tunisie",
    centralTunisia: "Centre de la Tunisie",
    southTunisia: "Sud de la Tunisie",
    deliveryRatesNote: "Les tarifs sont susceptibles de changer en fonction du poids et du volume de votre commande.",
    freeDeliveryTitle: "Livraison gratuite",
    freeDeliveryDescription: "Bénéficiez de la livraison gratuite dans les conditions suivantes :",
    freeDeliveryCondition1: "Pour toute commande supérieure à 150 DT",
    freeDeliveryCondition2: "Pour les membres Premium de notre programme de fidélité",
    freeDeliveryCondition3: "Lors de nos périodes promotionnelles spéciales",
    deliveryFaqTitle: "Questions fréquentes sur la livraison",
    deliveryFaq1Question: "Comment suivre ma commande ?",
    deliveryFaq1Answer: "Vous recevrez un email avec un numéro de suivi dès que votre commande sera expédiée. Vous pourrez suivre votre colis en temps réel depuis votre espace client ou directement sur le site du transporteur.",
    deliveryFaq2Question: "Que faire si je ne suis pas présent lors de la livraison ?",
    deliveryFaq2Answer: "Le livreur laissera un avis de passage et vous pourrez organiser une nouvelle livraison ou récupérer votre colis dans un point relais, selon les options proposées par le transporteur.",
    deliveryFaq3Question: "Les frais de livraison sont-ils remboursés en cas de retour ?",
    deliveryFaq3Answer: "Oui, si le retour est dû à une erreur de notre part ou à un produit défectueux. Dans le cas d'un simple changement d'avis, les frais de livraison initiaux ne sont pas remboursés.",
    deliveryFaq4Question: "Livrez-vous à l'international ?",
    deliveryFaq4Answer: "Actuellement, nous livrons uniquement en Tunisie. Nous travaillons à étendre notre service de livraison à d'autres pays prochainement.",
    deliveryContactTitle: "Vous avez d'autres questions ?",
    deliveryContactDescription: "Notre équipe de service client est disponible pour répondre à toutes vos questions concernant la livraison de vos commandes.",
    
    // Page FAQ
    faqPageTitle: "Questions Fréquemment Posées",
    faqPageSubtitle: "Trouvez rapidement des réponses à vos questions sur nos produits et services",
    faqSearchPlaceholder: "Rechercher dans les FAQ...",
    searchResultsFound: "{count} résultats trouvés",
    noSearchResults: "Aucun résultat trouvé",
    backToAllFaqs: "Retour à toutes les FAQ",
    popularQuestions: "Questions populaires",
    
    // Catégories de FAQ
    faqCategoryGeneral: "Général",
    faqCategoryGeneralDesc: "Questions générales sur notre site",
    faqCategoryOrders: "Commandes",
    faqCategoryOrdersDesc: "Tout sur vos commandes",
    faqCategoryShipping: "Livraison",
    faqCategoryShippingDesc: "Informations de livraison",
    faqCategoryPayment: "Paiement",
    faqCategoryPaymentDesc: "Options de paiement",
    faqCategoryReturns: "Retours",
    faqCategoryReturnsDesc: "Politique de retour",
    faqCategoryAccount: "Compte",
    faqCategoryAccountDesc: "Gestion de compte",
    faqCategoryProducts: "Produits",
    faqCategoryProductsDesc: "Informations sur nos produits",
    faqCategorySchool: "Listes Scolaires",
    faqCategorySchoolDesc: "Tout sur les listes scolaires",
    faqCategorySellers: "Vendeurs",
    faqCategorySellersDesc: "Informations pour les vendeurs",
    faqCategorySecurity: "Sécurité",
    faqCategorySecurityDesc: "Sécurité et confidentialité",
    
    // Questions populaires
    popularQuestion1: "Comment suivre ma commande ?",
    popularAnswer1: "Pour suivre votre commande, connectez-vous à votre compte, accédez à la section 'Mes commandes' et cliquez sur 'Suivre' à côté de la commande concernée. Vous pourrez voir le statut actuel et l'emplacement de votre colis.",
    popularQuestion2: "Quels sont les délais de livraison ?",
    popularAnswer2: "Les délais de livraison varient selon votre emplacement et le mode de livraison choisi. En général, la livraison standard prend 3-5 jours ouvrables, tandis que la livraison express prend 1-2 jours ouvrables.",
    popularQuestion3: "Comment puis-je payer mes achats ?",
    popularAnswer3: "Nous acceptons plusieurs méthodes de paiement : cartes de crédit/débit (Visa, Mastercard), PayPal, virement bancaire et paiement à la livraison dans certaines régions.",
    popularQuestion4: "Comment retourner un produit ?",
    popularAnswer4: "Pour retourner un produit, connectez-vous à votre compte, accédez à 'Mes commandes', trouvez la commande concernée, cliquez sur 'Retourner un article' et suivez les instructions pour imprimer l'étiquette de retour.",
    popularQuestion5: "Comment créer un compte ?",
    popularAnswer5: "Pour créer un compte, cliquez sur l'icône de profil en haut à droite, sélectionnez 'S'inscrire', remplissez le formulaire avec vos informations et créez un mot de passe. Vous recevrez un email de confirmation pour activer votre compte.",
    
    // FAQ Général
    faqGeneralQuestion1: "Qu'est-ce que PInventory ?",
    faqGeneralAnswer1: "PInventory est une marketplace spécialisée dans les articles de papeterie, fournitures de bureau et instruments d'écriture de qualité. Nous proposons une large gamme de produits provenant des meilleures marques ainsi que des vendeurs indépendants sélectionnés pour la qualité de leurs produits.",
    faqGeneralQuestion2: "Comment contacter le service client ?",
    faqGeneralAnswer2: "Vous pouvez contacter notre service client de plusieurs façons : par email à support@penventory.com, par téléphone au +216 71 123 456 (du lundi au vendredi, 9h-18h), via le chat en direct sur notre site, ou en remplissant le formulaire de contact dans la section 'Contact'.",
    faqGeneralQuestion3: "Quels sont vos horaires d'ouverture ?",
    faqGeneralAnswer3: "Notre service client est disponible du lundi au vendredi de 9h à 18h et le samedi de 9h à 13h. Notre site web est accessible 24h/24 et 7j/7 pour vos achats en ligne.",
    faqGeneralQuestion4: "Livrez-vous à l'international ?",
    faqGeneralAnswer4: "Actuellement, nous livrons uniquement en Tunisie. Nous travaillons à étendre notre service de livraison à d'autres pays prochainement.",
    
    // FAQ Commandes supplémentaires
    faqOrdersQuestion4: "Comment puis-je annuler une commande ?",
    faqOrdersAnswer4: "Vous pouvez annuler une commande uniquement si elle n'a pas encore été traitée. Pour ce faire, connectez-vous à votre compte, accédez à 'Mes commandes', trouvez la commande concernée et cliquez sur 'Annuler' si cette option est disponible.",
    faqOrdersQuestion5: "Puis-je modifier l'adresse de livraison après avoir passé ma commande ?",
    faqOrdersAnswer5: "Vous pouvez modifier l'adresse de livraison uniquement si votre commande n'a pas encore été traitée. Contactez notre service client dès que possible avec votre numéro de commande et la nouvelle adresse.",
    
    // FAQ Livraison
    faqShippingQuestion1: "Quelles sont les options de livraison disponibles ?",
    faqShippingAnswer1: "Nous proposons deux options de livraison : la livraison standard (3-5 jours ouvrables) et la livraison express (1-2 jours ouvrables). Les tarifs varient selon votre emplacement et le poids de votre commande.",
    faqShippingQuestion2: "Comment suivre ma livraison ?",
    faqShippingAnswer2: "Une fois votre commande expédiée, vous recevrez un email avec un numéro de suivi. Vous pouvez utiliser ce numéro pour suivre votre colis sur le site du transporteur ou dans la section 'Mes commandes' de votre compte.",
    faqShippingQuestion3: "Que faire si je ne suis pas présent lors de la livraison ?",
    faqShippingAnswer3: "Si vous n'êtes pas présent lors de la livraison, le livreur laissera un avis de passage. Vous pourrez alors organiser une nouvelle livraison ou récupérer votre colis dans un point relais, selon les options proposées par le transporteur.",
    faqShippingQuestion4: "La livraison est-elle gratuite ?",
    faqShippingAnswer4: "La livraison est gratuite pour toute commande supérieure à 150 DT, pour les membres Premium de notre programme de fidélité, et lors de nos périodes promotionnelles spéciales.",
    
    // FAQ Paiement supplémentaires
    faqPaymentQuestion4: "Mon paiement est-il sécurisé ?",
    faqPaymentAnswer4: "Oui, tous les paiements effectués sur notre site sont sécurisés. Nous utilisons un cryptage SSL pour protéger vos données personnelles et financières. Nous ne stockons pas vos informations de carte de crédit sur nos serveurs.",
    faqPaymentQuestion5: "Puis-je payer en plusieurs fois ?",
    faqPaymentAnswer5: "Oui, pour les commandes supérieures à 300 DT, nous proposons un paiement en 3 fois sans frais avec certaines cartes bancaires. Cette option est disponible lors du processus de paiement.",
    
    // FAQ Retours supplémentaires
    faqReturnsQuestion3: "Quelle est votre politique de retour ?",
    faqReturnsAnswer3: "Vous pouvez retourner un produit dans les 14 jours suivant sa réception si vous n'êtes pas satisfait. Le produit doit être dans son état d'origine, non utilisé et dans son emballage d'origine. Certains produits, comme les articles personnalisés, ne peuvent pas être retournés.",
    faqReturnsQuestion4: "Comment serai-je remboursé ?",
    faqReturnsAnswer4: "Une fois que nous aurons reçu et vérifié le produit retourné, nous procéderons au remboursement. Le remboursement sera effectué sur le même moyen de paiement que celui utilisé pour l'achat. Le délai de remboursement dépend de votre banque, mais prend généralement 5 à 10 jours ouvrables.",
    
    // FAQ Compte supplémentaire
    faqAccountQuestion4: "Comment supprimer mon compte ?",
    faqAccountAnswer4: "Pour supprimer votre compte, connectez-vous, accédez à 'Mon profil', puis à 'Paramètres du compte', et cliquez sur 'Supprimer mon compte'. Veuillez noter que cette action est irréversible et que toutes vos données seront définitivement supprimées.",
    
    // FAQ Produits
    faqProductsQuestion1: "Comment savoir si un produit est disponible ?",
    faqProductsAnswer1: "La disponibilité d'un produit est indiquée sur sa page produit. Si un produit est en stock, vous verrez la mention 'En stock' et vous pourrez l'ajouter à votre panier. Si un produit est épuisé, vous verrez la mention 'Rupture de stock'.",
    faqProductsQuestion2: "Les produits sont-ils garantis ?",
    faqProductsAnswer2: "Oui, tous nos produits bénéficient d'une garantie légale de conformité de 2 ans. Certains produits peuvent bénéficier d'une garantie supplémentaire du fabricant. Les détails de la garantie sont indiqués sur la page produit.",
    faqProductsQuestion3: "Comment savoir si un produit est authentique ?",
    faqProductsAnswer3: "Tous les produits vendus sur PInventory sont 100% authentiques. Nous travaillons directement avec les marques ou avec des revendeurs agréés. Chaque produit est vérifié avant expédition pour garantir son authenticité.",
    faqProductsQuestion4: "Puis-je acheter en gros ?",
    faqProductsAnswer4: "Oui, nous proposons des tarifs spéciaux pour les achats en gros. Si vous êtes une entreprise ou une institution et souhaitez commander en grande quantité, veuillez contacter notre service commercial à business@penventory.com pour obtenir un devis personnalisé.",
    
    // FAQ Listes Scolaires
    faqSchoolQuestion1: "Comment fonctionnent les listes scolaires ?",
    faqSchoolAnswer1: "Notre service de listes scolaires vous permet de commander facilement tous les articles nécessaires pour la rentrée scolaire. Il vous suffit de sélectionner l'école et la classe de votre enfant, et nous vous proposerons une liste prédéfinie que vous pourrez personnaliser selon vos besoins.",
    faqSchoolQuestion2: "Comment ajouter une école à la liste ?",
    faqSchoolAnswer2: "Si votre école n'est pas dans notre base de données, vous pouvez nous contacter à schools@penventory.com avec les informations de l'école (nom, adresse, contact) et les listes scolaires si vous les avez. Nous ajouterons l'école dans les plus brefs délais.",
    faqSchoolQuestion3: "Puis-je personnaliser une liste scolaire ?",
    faqSchoolAnswer3: "Oui, vous pouvez personnaliser une liste scolaire en ajoutant ou supprimant des articles selon vos besoins. Vous pouvez également ajuster les quantités de chaque article. Une fois la liste personnalisée, vous pouvez l'enregistrer et la commander en un clic.",
    faqSchoolQuestion4: "Y a-t-il des réductions pour les listes scolaires ?",
    faqSchoolAnswer4: "Oui, nous proposons des réductions spéciales pour les listes scolaires, notamment pendant la période de rentrée scolaire. De plus, la livraison est gratuite pour toute commande de liste scolaire, quelle que soit sa valeur.",
    
    // FAQ Vendeurs
    faqSellersQuestion1: "Comment devenir vendeur sur PInventory ?",
    faqSellersAnswer1: "Pour devenir vendeur sur PInventory, cliquez sur 'Devenir vendeur' en haut de la page, puis suivez les étapes d'inscription. Vous devrez fournir des informations sur votre entreprise, vos coordonnées bancaires et fiscales.",
    faqSellersQuestion2: "Quels sont les frais pour vendre sur PInventory ?",
    faqSellersAnswer2: "PInventory prélève une commission de 5% sur chaque vente réalisée sur la plateforme. Il n'y a pas de frais d'inscription ou d'abonnement mensuel.",
    faqSellersQuestion3: "Comment sont gérés les paiements ?",
    faqSellersAnswer3: "Les paiements sont sécurisés et traités par notre système. Une fois qu'une commande est livrée et confirmée par le client, vous pouvez demander un virement sur votre compte bancaire. Les paiements sont généralement traités sous 3 jours ouvrables.",
    faqSellersQuestion4: "Comment gérer mes produits et commandes ?",
    faqSellersAnswer4: "Une fois inscrit, vous aurez accès à un tableau de bord vendeur où vous pourrez ajouter, modifier et supprimer des produits, ainsi que gérer vos commandes, suivre vos ventes et communiquer avec les clients.",
    faqSellersQuestion5: "Puis-je vendre n'importe quel type de produit ?",
    faqSellersAnswer5: "Vous pouvez vendre la plupart des produits légaux liés à la papeterie et aux fournitures de bureau, mais certaines catégories sont restreintes ou interdites. Consultez nos conditions d'utilisation pour plus de détails sur les produits autorisés et interdits.",
    
    // FAQ Sécurité
    faqSecurityQuestion1: "Comment mes données personnelles sont-elles protégées ?",
    faqSecurityAnswer1: "Nous prenons très au sérieux la protection de vos données personnelles. Toutes les informations que vous nous fournissez sont cryptées et stockées de manière sécurisée. Nous ne partageons jamais vos données avec des tiers sans votre consentement explicite.",
    faqSecurityQuestion2: "Que faire si je soupçonne une activité frauduleuse sur mon compte ?",
    faqSecurityAnswer2: "Si vous soupçonnez une activité frauduleuse sur votre compte, changez immédiatement votre mot de passe et contactez notre service client à security@penventory.com. Nous examinerons votre compte et prendrons les mesures nécessaires pour le sécuriser.",
    faqSecurityQuestion3: "Comment créer un mot de passe sécurisé ?",
    faqSecurityAnswer3: "Pour créer un mot de passe sécurisé, utilisez au moins 8 caractères, incluant des lettres majuscules et minuscules, des chiffres et des caractères spéciaux. Évitez d'utiliser des informations personnelles facilement devinables comme votre date de naissance.",
    faqSecurityQuestion4: "PInventory utilise-t-il des cookies ?",
    faqSecurityAnswer4: "Oui, nous utilisons des cookies pour améliorer votre expérience sur notre site. Ces cookies nous permettent de mémoriser vos préférences, de vous proposer des contenus personnalisés et d'analyser notre trafic. Vous pouvez gérer vos préférences de cookies dans les paramètres de votre navigateur.",
    
    // Page About
    aboutUsTitle: "À propos de Penventory",
    aboutUsSubtitle: "Découvrez notre histoire, notre mission et les valeurs qui nous animent depuis plus de 15 ans dans le domaine de la papeterie et des fournitures de bureau.",
    ourStoryTitle: "Notre Histoire",
    ourStoryParagraph1: "Fondée en 2010 à Tunis, Penventory est née de la passion de son fondateur Moncef Ben Salem pour les instruments d'écriture de qualité et les articles de papeterie raffinés.",
    ourStoryParagraph2: "Ce qui a commencé comme une petite boutique dans le centre-ville de Tunis s'est transformé en une référence nationale pour les amateurs d'écriture, les professionnels et les étudiants à la recherche de produits de qualité supérieure.",
    ourStoryParagraph3: "Aujourd'hui, Penventory continue de croître tout en restant fidèle à ses valeurs fondamentales : qualité, service client exceptionnel et innovation constante.",
    storeLocation: "Rue de Carthage, Centre-ville de Tunis",
    
    // Page Terms of Use
    termsOfUseTitle: "Conditions d'utilisation",
    termsOfUseSubtitle: "Veuillez lire attentivement ces conditions d'utilisation avant d'utiliser notre site.",
    lastUpdated: "Dernière mise à jour :",
    tableOfContents: "Table des matières",
    viewPrivacyPolicy: "Voir la politique de confidentialité",
    privacyPolicyLink: "Consultez notre politique de confidentialité",
    contactEmail: "Email",
    contactAddress: "Adresse",
    companyAddress: "Rue de Carthage, Centre-ville de Tunis, Tunisie",
    
    // Sections des conditions d'utilisation
    termsSection1Title: "Introduction",
    termsSection1Para1: "Bienvenue sur PInventory. Les présentes conditions d'utilisation régissent votre utilisation de notre site web, y compris toutes les fonctionnalités et services disponibles via notre domaine et sous-domaines.",
    termsSection1Para2: "En accédant à ou en utilisant notre site, vous acceptez d'être lié par ces conditions. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser notre site.",
    termsSection1Para3: "Nous nous réservons le droit de modifier ces conditions à tout moment. Votre utilisation continue du site après la publication de modifications constitue votre acceptation de ces modifications.",
    
    termsSection2Title: "Définitions",
    termsSection2Para1: "Dans ces conditions d'utilisation, les termes suivants ont les significations suivantes :",
    termsDefinition1Title: "Site",
    termsDefinition1: "Le site web PInventory, accessible via www.penventory.com et tous ses sous-domaines.",
    termsDefinition2Title: "Utilisateur",
    termsDefinition2: "Toute personne qui accède au site ou utilise ses services.",
    termsDefinition3Title: "Compte",
    termsDefinition3: "Un compte enregistré sur le site permettant l'accès à des fonctionnalités supplémentaires.",
    termsDefinition4Title: "Contenu",
    termsDefinition4: "Tout texte, images, vidéos, données ou autres matériels téléchargés, publiés ou autrement rendus disponibles sur le site.",
    termsDefinition5Title: "Services",
    termsDefinition5: "Toutes les fonctionnalités, outils et services offerts par PInventory.",
    
    termsSection3Title: "Comptes utilisateurs",
    termsSection3Para1: "Pour accéder à certaines fonctionnalités du site, vous devrez créer un compte. Vous êtes responsable de maintenir la confidentialité de votre compte et mot de passe et de restreindre l'accès à votre ordinateur.",
    termsSection3Para2: "Vous acceptez d'être responsable de toutes les activités qui se produisent sous votre compte. Si vous pensez que votre compte a été compromis, veuillez nous contacter immédiatement.",
    termsSection3Para3: "Vous devez fournir des informations exactes, complètes et à jour lors de l'inscription. Si vos informations changent, vous devez les mettre à jour dès que possible.",
    termsSection3Para4: "Nous nous réservons le droit de refuser l'accès, de fermer des comptes ou de supprimer ou modifier du contenu à notre seule discrétion.",
    
    termsSection4Title: "Services et prix",
    termsSection4Para1: "PInventory est une marketplace qui permet aux vendeurs de proposer leurs produits à la vente et aux acheteurs de les acheter. Nous ne sommes pas propriétaires des produits vendus et n'en garantissons pas la qualité, la sécurité ou la légalité.",
    termsSection4Para2: "Les prix des produits sont déterminés par les vendeurs. Tous les prix sont en Dinars Tunisiens (DT) et incluent la TVA applicable, sauf indication contraire.",
    termsSection4Para3: "Nous nous réservons le droit de modifier ou d'interrompre tout service sans préavis. Nous ne serons pas responsables envers vous ou un tiers pour toute modification, suspension ou interruption des services.",
    
    termsSection5Title: "Contenu utilisateur",
    termsSection5Para1: "Notre site permet aux utilisateurs de publier, lier, stocker, partager et rendre disponible certaines informations, textes, graphiques, vidéos ou autres matériels. Vous êtes responsable du contenu que vous publiez sur le site.",
    termsSection5Para2: "En publiant du contenu sur notre site, vous nous accordez une licence mondiale, non exclusive, libre de redevance, transférable et pouvant faire l'objet d'une sous-licence pour utiliser, reproduire, modifier, adapter, publier, traduire, distribuer et afficher ce contenu.",
    termsSection5Para3: "Vous garantissez que tout contenu que vous publiez est exact, n'est pas trompeur, et ne viole pas les droits de tiers, y compris les droits de propriété intellectuelle. Nous nous réservons le droit de supprimer tout contenu qui viole ces conditions ou que nous jugeons autrement inacceptable.",
    
    termsSection6Title: "Propriété intellectuelle",
    termsSection6Para1: "Le site et tout son contenu original, fonctionnalités et fonctionnalités sont et resteront la propriété exclusive de PInventory et sont protégés par les lois tunisiennes et internationales sur le droit d'auteur, les marques de commerce, les brevets, les secrets commerciaux et autres lois sur la propriété intellectuelle ou les droits de propriété.",
    termsSection6Para2: "Vous ne pouvez pas reproduire, distribuer, modifier, créer des œuvres dérivées, afficher publiquement, exécuter publiquement, republier, télécharger, stocker ou transmettre tout matériel de notre site, sauf si cela est expressément autorisé par ces conditions.",
    termsSection6Para3: "Rien dans ces conditions ne vous confère de droits, titres ou intérêts dans le site ou son contenu, ni aucun droit d'utiliser les marques de commerce, logos, noms de domaine ou autres caractéristiques distinctives de la marque PInventory.",
    
    termsSection7Title: "Confidentialité",
    termsSection7Para1: "Votre utilisation de notre site est également régie par notre politique de confidentialité, qui est incorporée ici par référence.",
    termsSection7Para2: "En utilisant notre site, vous consentez à la collecte, à l'utilisation et au partage de vos informations comme décrit dans notre politique de confidentialité.",
    
    termsSection8Title: "Résiliation",
    termsSection8Para1: "Nous pouvons résilier ou suspendre votre compte et votre accès au site immédiatement, sans préavis ni responsabilité, pour quelque raison que ce soit, y compris, sans limitation, si vous violez ces conditions.",
    termsSection8Para2: "À la résiliation, votre droit d'utiliser le site cessera immédiatement. Si vous souhaitez résilier votre compte, vous pouvez simplement cesser d'utiliser le site ou nous contacter pour demander la suppression de votre compte.",
    
    termsSection9Title: "Limitation de responsabilité",
    termsSection9Para1: "En aucun cas, PInventory, ses directeurs, employés, partenaires, agents, fournisseurs ou affiliés ne seront responsables de tout dommage indirect, accessoire, spécial, consécutif ou punitif, y compris, sans limitation, la perte de profits, de données, d'utilisation, de bonne volonté ou d'autres pertes immatérielles, résultant de votre accès ou de votre utilisation ou de votre incapacité à accéder ou à utiliser le site.",
    termsSection9Para2: "Nous ne sommes pas responsables des actions, du contenu, des informations ou des données de tiers, et vous nous libérez, nos directeurs, employés et agents de toute réclamation et dommages, connus et inconnus, découlant de ou liés de quelque manière que ce soit à toute réclamation que vous avez contre de tels tiers.",
    termsSection9Para3: "Certaines juridictions ne permettent pas l'exclusion ou la limitation de responsabilité pour les dommages consécutifs ou accessoires, donc certaines des limitations ci-dessus peuvent ne pas s'appliquer à vous.",
    
    termsSection10Title: "Loi applicable",
    termsSection10Para1: "Ces conditions sont régies et interprétées conformément aux lois de la Tunisie, sans égard à ses dispositions en matière de conflit de lois.",
    termsSection10Para2: "Notre incapacité à faire respecter tout droit ou disposition de ces conditions ne sera pas considérée comme une renonciation à ces droits. Si une disposition de ces conditions est jugée invalide ou inapplicable par un tribunal, les dispositions restantes de ces conditions resteront en vigueur.",
    
    termsSection11Title: "Modifications des conditions",
    termsSection11Para1: "Nous nous réservons le droit, à notre seule discrétion, de modifier ou de remplacer ces conditions à tout moment. Si une révision est importante, nous fournirons un préavis d'au moins 30 jours avant que les nouvelles conditions ne prennent effet.",
    termsSection11Para2: "En continuant à accéder ou à utiliser notre site après que ces révisions deviennent effectives, vous acceptez d'être lié par les conditions révisées. Si vous n'acceptez pas les nouvelles conditions, veuillez cesser d'utiliser le site.",
    
    termsSection12Title: "Nous contacter",
    termsSection12Para1: "Si vous avez des questions concernant ces conditions, veuillez nous contacter :",
    missionVisionTitle: "Notre Mission & Vision",
    ourMissionTitle: "Notre Mission",
    ourMissionDescription: "Fournir des produits d'écriture et de papeterie de la plus haute qualité qui inspirent la créativité, facilitent la productivité et enrichissent l'expérience d'écriture quotidienne de nos clients.",
    ourVisionTitle: "Notre Vision",
    ourVisionDescription: "Devenir la référence incontournable en Tunisie et en Afrique du Nord pour tous les besoins en papeterie et fournitures de bureau, en combinant tradition artisanale et innovation moderne.",
    ourValuesTitle: "Nos Valeurs",
    qualityValue: "Qualité",
    qualityValueDescription: "Nous ne proposons que des produits soigneusement sélectionnés répondant à nos normes élevées de qualité et de durabilité.",
    customerValue: "Service Client",
    customerValueDescription: "Nous plaçons nos clients au centre de toutes nos décisions et nous efforçons de dépasser leurs attentes à chaque interaction.",
    excellenceValue: "Excellence",
    excellenceValueDescription: "Nous visons l'excellence dans tous les aspects de notre entreprise, de la sélection des produits au service après-vente.",
    innovationValue: "Innovation",
    innovationValueDescription: "Nous recherchons constamment de nouveaux produits et solutions pour améliorer l'expérience d'écriture et de travail de nos clients.",
    growthValue: "Croissance",
    growthValueDescription: "Nous encourageons la croissance personnelle et professionnelle de notre équipe, ainsi que la croissance durable de notre entreprise.",
    reliabilityValue: "Fiabilité",
    reliabilityValueDescription: "Nous tenons nos promesses et sommes un partenaire fiable pour nos clients, fournisseurs et collaborateurs.",
    ourTeamTitle: "Notre Équipe",
    founderCEO: "Fondateur & PDG",
    marketingDirector: "Directrice Marketing",
    productManager: "Responsable Produits",
    customerServiceManager: "Responsable Service Client",
    ahmedBio: "Passionné par les instruments d'écriture depuis son plus jeune âge, Moncef a fondé Penventory avec la vision de partager cette passion avec le plus grand nombre.",
    leilaBio: "Avec plus de 10 ans d'expérience en marketing, Ala dirige toutes les initiatives de marketing et de communication de Penventory.",
    karimBio: "Expert en produits de papeterie, Karim est responsable de la sélection et du développement de notre gamme de produits.",
    soniaBio: "Sonia veille à ce que chaque client reçoive un service exceptionnel et une assistance personnalisée pour tous ses besoins.",
    whyChooseUsTitle: "Pourquoi Nous Choisir",
    qualityProductsTitle: "Produits de Qualité",
    qualityProductsDescription: "Nous proposons uniquement des produits de haute qualité, soigneusement sélectionnés auprès des meilleurs fabricants mondiaux.",
    expertiseTitle: "Expertise & Conseil",
    expertiseDescription: "Notre équipe d'experts passionnés vous guide dans le choix des produits parfaitement adaptés à vos besoins spécifiques.",
    customerServiceTitle: "Service Client Exceptionnel",
    customerServiceDescription: "Nous nous engageons à offrir une expérience d'achat agréable et un service après-vente réactif et efficace.",
    joinUsTitle: "Rejoignez la Communauté Penventory",
    joinUsDescription: "Découvrez notre sélection de produits exceptionnels et rejoignez des milliers de clients satisfaits qui font confiance à Penventory pour leurs besoins en papeterie et fournitures de bureau.",
    exploreProducts: "Explorer nos produits",
    
    // Page Wishlist
    myWishlist: "Ma liste de souhaits",
    emptyWishlist: "Votre liste de souhaits est vide",
    emptyWishlistMessage: "Vous n'avez pas encore ajouté de produits à votre liste de souhaits. Parcourez notre catalogue et ajoutez vos produits préférés !",
    continueShopping: "Continuer mes achats",
    clearWishlist: "Vider la liste",
    confirmClearWishlist: "Êtes-vous sûr de vouloir vider votre liste de souhaits ?",
    wishlistCleared: "Votre liste de souhaits a été vidée",
    wishlistItemRemoved: "Produit retiré de la liste de souhaits",
    wishlistLoadError: "Erreur lors du chargement de la liste de souhaits",
    wishlistRemoveError: "Erreur lors de la suppression du produit",
    addedToCart: "Produit ajouté au panier",
    addToCartError: "Erreur lors de l'ajout au panier",
    removeFromWishlist: "Retirer de la liste",
    product: "Produit",
    price: "Prix",
    status: "Statut",
    actions: "Actions",
    item: "article",
    items: "articles",
    inStock: "En stock",
    outOfStock: "Rupture de stock",
    priceUnavailable: "Prix non disponible",
    viewCart: "Voir le panier",
    currency: "Dt",
  },
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    categories: 'Categories',
    cart: 'Cart',
    account: 'Account',
    dashboard: 'Dashboard',
    orders: 'Orders',
    sellers: 'Sellers',
    customers: 'Customers',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    contact: 'Contact',
    help: 'Help',
    schoolLists: 'School Lists',
    becomeSeller: 'Become a Seller',
    favorites: 'Favorites',
    wishlist: 'Wishlist',
    delivery: 'Delivery',
    myOrders: 'My Orders',
    myAccount: 'My Account',
    profile: 'Profile',
    myStore: 'My Store',
    administration: 'Administration',
    management: 'Management',
    sellerSpace: 'Seller Space',
    
    // Actions
    search: 'Search',
    searchPlaceholder: 'Search for products...',
    filter: 'Filter',
    sort: 'Sort',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    subscribe: 'Subscribe',
    
    // Products
    price: 'Price',
    stock: 'Stock',
    description: 'Description',
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    
    // Orders
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    orderStatus: 'Order Status',
    orderTotal: 'Order Total',
    
    // Statuses
    pending: 'Pending',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    
    // Messages
    welcome: 'Welcome',
    noItems: 'No items found',
    lowStockFor: 'Low stock for "{product}"',
    minutesAgo: '{minutes} minutes ago',
    hoursAgo: '{hours} hour(s) ago',
    
    // Theme
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    
    // Language
    language: 'Language',
    french: 'French',
    english: 'English',
    selectLanguage: 'Select Language',
    
    // Footer
    aboutUs: 'About Us',
    aboutUsText: 'Your online marketplace for all your buying and selling needs.',
    quickLinks: 'Quick Links',
    about: 'About',
    faq: 'FAQ',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    newsletter: 'Newsletter',
    newsletterText: 'Sign up to receive our latest offers and promotions.',
    emailPlaceholder: 'Your email address',
    allRightsReserved: 'All rights reserved.',
    
    // Become Seller Page
    becomeSellerTitle: 'WANT TO SELL?',
    becomeSellerSubtitle: 'Become a seller on Penventory!',
    becomeSellerDescription: 'Join our marketplace and reach thousands of potential customers. Sell your products easily and grow your business with us.',
    becomeSellerButton: 'BECOME A SELLER',
    sellerStepsTitle: 'REALLY EASY TO SET UP AND CUSTOMIZE',
    sellerStep1Title: 'Create an account',
    sellerStep1Description: 'Create a seller account on PInventory to start selling your products.',
    sellerStep2Title: 'Create your profile',
    sellerStep2Description: 'Complete your seller profile with all the necessary information.',
    sellerStep3Title: 'Add your coordinates',
    sellerStep3Description: 'Add your banking and tax information to receive your payments.',
    sellerStep4Title: 'Add your product list',
    sellerStep4Description: 'Create your product catalog with detailed descriptions and quality images.',
    sellerStep5Title: 'Sell your products and earn points',
    sellerStep5Description: 'Start selling and earn loyalty points to unlock exclusive benefits.',
    sellerBenefitsTitle: 'WHY SELL ON PENVENTORY?',
    benefit1Title: 'Important Buyers',
    benefit1Description: 'Access a wide customer base, with many regular buyers.',
    benefit2Title: 'Fast Payments',
    benefit2Description: 'Once products are delivered to customers, you can request your payment immediately.',
    benefit3Title: 'Earn Badges',
    benefit3Description: 'Earn performance badges that set you apart as a professional seller.',
    benefit4Title: 'Customize Profile',
    benefit4Description: 'Customize your profile with information such as logo, location, and return policies.',
    benefit5Title: 'Add Media',
    benefit5Description: 'Integrate YouTube videos to make your store more authentic and stand out.',
    callToActionTitle: 'READY TO START YOUR SELLING ADVENTURE?',
    callToActionDescription: 'Join thousands of sellers who have already increased their revenue by selling on Penventory.',
    signUpAsSeller: 'SIGN UP AS A SELLER',
    faqTitle: 'FREQUENTLY ASKED QUESTIONS',
    faq1Question: 'How can I register as a seller?',
    faq1Answer: 'To register as a seller, click on the "Become a Seller" button at the top of this page, then follow the registration steps. You will need to provide information about your business, your banking and tax details.',
    faq2Question: 'What are the fees for selling on Penventory?',
    faq2Answer: 'Penventory takes a 5% commission on each sale made on the platform. There are no registration or monthly subscription fees.',
    faq3Question: 'How are payments managed?',
    faq3Answer: 'Payments are secure and processed by our system. Once an order is delivered and confirmed by the customer, you can request a transfer to your bank account. Payments are typically processed within 3 business days.',
    faq4Question: 'How do I manage my products and orders?',
    faq4Answer: 'Once registered, you will have access to a seller dashboard where you can add, edit, and delete products, as well as manage your orders, track your sales, and communicate with customers.',
    faq5Question: 'Can I sell any type of product?',
    faq5Answer: 'You can sell most legal products, but some categories are restricted or prohibited. Please refer to our terms of use for more details on allowed and prohibited products.',
    helpSectionTitle: 'Stuck? Ask Questions',
    helpSectionDescription: 'If you have questions about the selling process, don\'t hesitate to contact us. We\'re here to help!',
    helpCenter: 'Help Center',
    liveChat: 'Live Chat',
    
    // Help Page
    helpPageTitle: 'Help Center',
    helpPageSubtitle: 'How can we help you today?',
    searchPlaceholder: 'Type keywords like "return"',
    searchButton: 'Search',
    helpCategory1Title: 'Place an Order',
    helpCategory1Description: 'Everything you need to know about placing an order on our platform.',
    helpCategory2Title: 'Track Your Package',
    helpCategory2Description: 'How to track your orders and know their delivery status.',
    helpCategory3Title: 'Payment Methods',
    helpCategory3Description: 'Information about the different payment methods available.',
    helpCategory4Title: 'Cancel Orders',
    helpCategory4Description: 'How to cancel an order or make a return.',
    helpCategory5Title: 'Manage Your Account',
    helpCategory5Description: 'All about managing your account and personal information.',
    needMoreHelp: 'Need More Help?',
    needMoreHelpDescription: 'If you can\'t find the answer to your question, don\'t hesitate to contact our support team.',
    contactUs: 'Contact Us',
    
    // FAQ Orders
    faqOrder1Question: 'How do I place an order on PInventory?',
    faqOrder1Answer: 'To place an order on PInventory, follow these simple steps:\n      1. Browse our catalog and find the products you\'re interested in\n      2. Add products to your cart by clicking the "Add to Cart" button\n      3. Access your cart by clicking the cart icon in the top right\n      4. Review your order and click "Checkout"\n      5. Fill in your shipping and payment information\n      6. Confirm your order',
    faqOrder2Question: 'Can I modify my order after placing it?',
    faqOrder2Answer: 'You can modify your order only if it has not been processed yet. To do this, go to your account, view your recent orders, and click "Modify" if this option is available. If your order has already been processed, you will need to contact our customer service for assistance.',
    faqOrder3Question: 'How can I check product availability?',
    faqOrder3Answer: 'Product availability is indicated on the product page. If a product is in stock, you will see "In Stock" and you can add it to your cart. If a product is out of stock, you will see "Out of Stock" and you can sign up to be notified when it becomes available again.',
    
    // FAQ Tracking
    faqTracking1Question: 'How do I track my order?',
    faqTracking1Answer: 'To track your order, follow these steps:\n      1. Log in to your account\n      2. Go to the "My Orders" section\n      3. Find the order you want to track\n      4. Click "Track My Order"\n      \n      You will be able to see the current status of your order and the location of your package if delivery is in progress.',
    faqTracking2Question: 'What are the different delivery statuses?',
    faqTracking2Answer: 'Here are the different delivery statuses you might see:\n      - Order received: We have received your order\n      - Processing: Your order is being prepared\n      - Shipped: Your order has been handed over to the carrier\n      - In transit: Your order is on its way to you\n      - Delivered: Your order has been delivered to the address provided\n      - Delayed: There is a delay in the delivery of your order',
    faqTracking3Question: 'How long does it take to deliver my order?',
    faqTracking3Answer: 'Delivery time depends on your location and the delivery method chosen. In general, delivery times are as follows:\n      - Standard delivery: 3-5 business days\n      - Express delivery: 1-2 business days\n      \n      You can see the estimated delivery time when placing your order.',
    
    // FAQ Payment
    faqPayment1Question: 'What payment methods are accepted?',
    faqPayment1Answer: 'We accept several payment methods for your convenience:\n      - Credit/debit cards (Visa, Mastercard)\n      - PayPal\n      - Bank transfer\n      - Cash on delivery (for certain regions)',
    faqPayment2Question: 'Is my payment information secure?',
    faqPayment2Answer: 'Yes, all payment information is secure. We use SSL encryption to protect your personal and financial data. We do not store your credit card information on our servers.',
    faqPayment3Question: 'When will my account be charged?',
    faqPayment3Answer: 'Your account will be charged at the time you place your order. If a product is not available or if your order is canceled for any reason, you will be fully refunded.',
    
    // FAQ Returns
    faqReturns1Question: 'How do I cancel my order?',
    faqReturns1Answer: 'To cancel your order, follow these steps:\n      1. Log in to your account\n      2. Go to the "My Orders" section\n      3. Find the order you want to cancel\n      4. Click "Cancel Order"\n      \n      Please note that you can only cancel an order if it has not been shipped yet. If your order has already been shipped, you will need to return it once received.',
    faqReturns2Question: 'How do I return a product?',
    faqReturns2Answer: 'To return a product, follow these steps:\n      1. Log in to your account\n      2. Go to the "My Orders" section\n      3. Find the order containing the product you want to return\n      4. Click "Return an item"\n      5. Follow the instructions to print the return label\n      \n      Once we have received and verified the returned product, we will process the refund.',
    
    // FAQ Account
    faqAccount1Question: 'How do I create an account?',
    faqAccount1Answer: 'To create an account on PInventory, follow these steps:\n      1. Click on the profile icon at the top right of the page\n      2. Select "Sign Up"\n      3. Fill out the form with your personal information\n      4. Create a secure password\n      5. Click "Create Account"\n      \n      You will receive a confirmation email to activate your account.',
    faqAccount2Question: 'How do I update my personal information?',
    faqAccount2Answer: 'To update your personal information, follow these steps:\n      1. Log in to your account\n      2. Go to the "My Profile" section\n      3. Click "Edit" next to the information you want to update\n      4. Make your changes\n      5. Click "Save"\n      \n      Your information will be updated immediately.',
    faqAccount3Question: 'How do I reset my password?',
    faqAccount3Answer: 'If you forgot your password, follow these steps:\n      1. Click on the profile icon at the top right of the page\n      2. Select "Login"\n      3. Click on "Forgot password"\n      4. Enter the email address associated with your account\n      5. Click on "Reset password"\n      \n      You will receive an email with a link to reset your password.',
    
    // Chat support translations
    chatSupportTitle: "Chat Support",
    chatWelcomeTitle: "Welcome",
    chatWelcomeDescription: "How can we help you?",
    contactInfoTitle: "Contact Information",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    validate: "Submit",
    chooseOption: "Please choose one of the following options",
    back: "Back",
    typingPlaceholder: "Type your message...",
    cannotTypeNow: "You cannot type now",
    
    // Support categories
    supportCategory1: "Placing an order",
    supportCategory2: "Account settings",
    supportCategory3: "Payment and vouchers",
    supportCategory4: "Other general inquiry",
    supportCategory5: "Order-related inquiry",
    
    // Chat messages
    chatWelcomeMessage: "Hello {firstName}, I'm the virtual assistant. I'm here to answer your questions.",
    chatCategoryMessage: "Please choose one of the following options regarding \"{categoryLabel}\"",
    chatNoPredefResponse: "I don't have a predefined answer for this question. Would you like to speak to an agent?",
    chatAgentSoon: "Thank you for your message. An agent will respond as soon as possible.",
    chatHelpWithElse: "Can I help you with anything else?",
    chatConnectAgent: "We will connect you with an agent. Please wait a moment.",
    chatThanks: "Thank you for using our chat service. Feel free to come back if you have any other questions!",
    chatClosed: "The conversation has been closed",
    
    // Quick replies
    quickReplyYesAgent: "Yes, I want to speak to an agent",
    quickReplyNoThanks: "No, thank you",
    quickReplyNewConversation: "New conversation",
    quickReplyAnotherQuestion: "Yes, I have another question",
    
    // Chat FAQ questions
    chatFaqOrder1: "How do I place an order?",
    chatFaqOrder2: "Can I modify my order after placing it?",
    chatFaqAccount1: "How do I update my personal information?",
    chatFaqAccount2: "How do I change my password?",
    chatFaqPayment1: "How do I make a payment with a credit card?",
    chatFaqPayment2: "How do I use a voucher?",
    chatFaqPayment3: "Check my credit balance",
    chatFaqGeneral1: "How do I contact customer service?",
    chatFaqGeneral2: "What are your opening hours?",
    chatFaqOrderRelated1: "When will my order be delivered?",
    chatFaqOrderRelated2: "How do I track my delivery?",
    chatFaqOrderRelated3: "Can I change my delivery address?",
    
    // Predefined responses
    predefinedResponseOrder1: "To place an order, follow these steps:\n    1. Browse our catalog and add the desired products to your cart\n    2. Click on the cart icon to view your selection\n    3. Click on \"Checkout\"\n    4. Fill in your shipping and payment information\n    5. Confirm your order",
    predefinedResponsePayment3Step1: "To check your credit balance you can:",
    predefinedResponsePayment3Step2: "1. Log in to your account",
    predefinedResponsePayment3Step3: "2. Click on \"account\" then credit",
    predefinedResponsePayment3Step4: "OR",
    predefinedResponsePayment3Step5: "1. Log in to your account via web or application",
    predefinedResponsePayment3Step6: "2. Check the balance under the \"Credit\" section",
    predefinedResponseOrderRelated2Step1: "To track your delivery:",
    predefinedResponseOrderRelated2Step2: "1. Log in to your account",
    predefinedResponseOrderRelated2Step3: "2. Go to \"My orders\"",
    predefinedResponseOrderRelated2Step4: "3. Select the order in question",
    predefinedResponseOrderRelated2Step5: "4. Click on \"Track my delivery\"",
    
    // Contact page
    contactPageTitle: "Contact Us",
    contactPageSubtitle: "We're here to help. Fill out the form below and we'll get back to you as soon as possible.",
    contactInfoTitle: "Contact Information",
    emailLabel: "Email",
    phoneLabel: "Phone",
    addressLabel: "Address",
    openingHoursTitle: "Opening Hours",
    openingHoursContent: "Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 9:00 AM - 1:00 PM\nSunday: Closed",
    sendMessageTitle: "Send Us a Message",
    fullNameLabel: "Full Name",
    subjectLabel: "Subject",
    orderNumberLabel: "Order Number (if applicable)",
    categoryLabel: "Category",
    priorityLabel: "Priority",
    messageLabel: "Message",
    sendingButton: "Sending...",
    sendButton: "Send Message",
    thankYouTitle: "Thank You for Your Message!",
    thankYouMessage: "Your request has been successfully submitted. Our support team will get back to you as soon as possible.",
    referenceNumberLabel: "Reference Number:",
    keepReferenceMessage: "Please keep this reference number for tracking your request.",
    submitAnotherRequest: "Submit Another Request",
    faqTitle: "Frequently Asked Questions",
    trackOrderQuestion: "How do I track my order?",
    trackOrderAnswer: "Log in to your account, go to \"My Orders\" and click on \"Track\" next to your order.",
    returnPolicyQuestion: "Return Policy",
    returnPolicyAnswer: "You can return a product within 14 days of receipt if you are not satisfied.",
    paymentMethodsQuestion: "Payment Methods",
    paymentMethodsAnswer: "We accept credit/debit cards, cash on delivery, and bank transfers.",
    
    // Support categories
    contactCategoryPayment: "Payment",
    contactCategoryShipping: "Shipping",
    contactCategoryProduct: "Product",
    contactCategoryAccount: "Account",
    contactCategoryOther: "Other",
    
    // Support priorities
    contactPriorityLow: "Low",
    contactPriorityMedium: "Medium",
    contactPriorityHigh: "High",
    contactPriorityUrgent: "Urgent",
    
    // Toast messages
    contactSuccessMessage: "Your request has been submitted successfully!",
    contactErrorAuth: "Please log in to submit a support ticket.",
    contactErrorGeneral: "An error occurred. Please try again.",
    
    // Home page
    homeCategories: "Pen Categories",
    homeFeaturedProducts: "Featured Products",
    homeFeaturedProductsSubtitle: "Discover our selection of luxury pens",
    homeBrands: "Our Partner Brands",
    homeBrandsSubtitle: "The biggest brands trust us",
    homeViewAll: "View all",
    homeAddToCart: "Add to cart",
    homeReviews: "reviews",
    homeLowStock: "Only {stock} left in stock",
    homeOutOfStock: "Out of stock",
    homeAdvantage1Title: "Premium Quality",
    homeAdvantage1Subtitle: "Rigorous product selection",
    homeAdvantage2Title: "Authentic Guarantee",
    homeAdvantage2Subtitle: "100% authentic products",
    homeAdvantage3Title: "Fast Delivery",
    homeAdvantage3Subtitle: "Shipping within 24 hours",
    
    // API errors
    errorCategories: "Error retrieving categories",
    errorProducts: "Error retrieving featured products",
    errorBrands: "Error retrieving brands",
    
    // Default categories
    defaultCategory1: "Luxury Pens",
    defaultCategory2: "Fountain Pens",
    defaultCategory3: "Ballpoint Pens",
    defaultCategory4: "Rollerball Pens",
    defaultCategory5: "Pencils & Mechanical Pencils",
    defaultCategory6: "Writing Accessories",
    
    // Page Livraison
    deliveryTitle: "All About Our Delivery Solutions",
    deliverySubtitle: "We offer different delivery options to meet your needs. Discover our rates and delivery times.",
    deliveryInfoTitle: "Our Delivery Services",
    deliveryInfoDescription: "We work with the best carriers to offer you a quality service. Here are the different options available:",
    standardDelivery: "Standard Delivery",
    standardDeliveryDescription: "Economical delivery for your regular orders, with package tracking.",
    expressDelivery: "Express Delivery",
    expressDeliveryDescription: "Fast delivery for your urgent orders, with guaranteed delivery time.",
    deliveryTime: "Delivery Times",
    deliveryTimeDescription: "Our delivery times vary depending on your location and the type of delivery chosen.",
    secureDelivery: "Secure Delivery",
    secureDeliveryDescription: "All our packages are carefully packed and insured during transport.",
    deliveryRatesTitle: "Delivery Rates",
    deliveryZone: "Delivery Zone",
    standardRate: "Standard Rate",
    expressRate: "Express Rate",
    greaterTunis: "Greater Tunis",
    northTunisia: "Northern Tunisia",
    centralTunisia: "Central Tunisia",
    southTunisia: "Southern Tunisia",
    deliveryRatesNote: "Rates are subject to change based on the weight and volume of your order.",
    freeDeliveryTitle: "Free Delivery",
    freeDeliveryDescription: "Benefit from free delivery under the following conditions:",
    freeDeliveryCondition1: "For any order over 150 DT",
    freeDeliveryCondition2: "For Premium members of our loyalty program",
    freeDeliveryCondition3: "During our special promotional periods",
    deliveryFaqTitle: "Frequently Asked Questions About Delivery",
    deliveryFaq1Question: "How can I track my order?",
    deliveryFaq1Answer: "You will receive an email with a tracking number as soon as your order is shipped. You can track your package in real-time from your customer account or directly on the carrier's website.",
    deliveryFaq2Question: "What if I'm not present during delivery?",
    deliveryFaq2Answer: "The delivery person will leave a delivery notice and you can arrange for a new delivery or pick up your package at a relay point, depending on the options offered by the carrier.",
    deliveryFaq3Question: "Are delivery fees refunded in case of return?",
    deliveryFaq3Answer: "Yes, if the return is due to an error on our part or a defective product. In the case of a simple change of mind, the initial delivery costs are not refunded.",
    deliveryFaq4Question: "Do you deliver internationally?",
    deliveryFaq4Answer: "Currently, we only deliver in Tunisia. We are working to extend our delivery service to other countries soon.",
    deliveryContactTitle: "Do you have other questions?",
    deliveryContactDescription: "Our customer service team is available to answer all your questions regarding the delivery of your orders.",
    
    // Page About
    aboutUsTitle: "About Penventory",
    aboutUsSubtitle: "Discover our story, our mission, and the values that have driven us for over 15 years in the stationery and office supplies industry.",
    ourStoryTitle: "Our Story",
    ourStoryParagraph1: "Founded in 2010 in Tunis, Penventory was born from the passion of its founder Moncef Ben Salem for quality writing instruments and refined stationery items.",
    ourStoryParagraph2: "What began as a small shop in downtown Tunis has transformed into a national reference for writing enthusiasts, professionals, and students looking for superior quality products.",
    ourStoryParagraph3: "Today, Penventory continues to grow while remaining true to its core values: quality, exceptional customer service, and constant innovation.",
    storeLocation: "Carthage Street, Downtown Tunis",
    missionVisionTitle: "Our Mission & Vision",
    ourMissionTitle: "Our Mission",
    ourMissionDescription: "To provide the highest quality writing and stationery products that inspire creativity, facilitate productivity, and enrich the daily writing experience of our customers.",
    ourVisionTitle: "Our Vision",
    ourVisionDescription: "To become the undisputed reference in Tunisia and North Africa for all stationery and office supply needs, combining traditional craftsmanship with modern innovation.",
    ourValuesTitle: "Our Values",
    qualityValue: "Quality",
    qualityValueDescription: "We only offer carefully selected products that meet our high standards of quality and durability.",
    customerValue: "Customer Service",
    customerValueDescription: "We place our customers at the center of all our decisions and strive to exceed their expectations with every interaction.",
    excellenceValue: "Excellence",
    excellenceValueDescription: "We aim for excellence in all aspects of our business, from product selection to after-sales service.",
    innovationValue: "Innovation",
    innovationValueDescription: "We constantly seek new products and solutions to improve the writing and work experience of our customers.",
    growthValue: "Growth",
    growthValueDescription: "We encourage the personal and professional growth of our team, as well as the sustainable growth of our business.",
    reliabilityValue: "Reliability",
    reliabilityValueDescription: "We keep our promises and are a reliable partner for our customers, suppliers, and collaborators.",
    ourTeamTitle: "Our Team",
    founderCEO: "Founder & CEO",
    marketingDirector: "Marketing Director",
    productManager: "Product Manager",
    customerServiceManager: "Customer Service Manager",
    ahmedBio: "Passionate about writing instruments from a young age, Moncef founded Penventory with the vision of sharing this passion with as many people as possible.",
    leilaBio: "With over 10 years of experience in marketing, Ala leads all of Penventory's marketing and communication initiatives.",
    karimBio: "An expert in stationery products, Karim is responsible for selecting and developing our product range.",
    soniaBio: "Sonia ensures that every customer receives exceptional service and personalized assistance for all their needs.",
    whyChooseUsTitle: "Why Choose Us",
    qualityProductsTitle: "Quality Products",
    qualityProductsDescription: "We offer only high-quality products, carefully selected from the best manufacturers worldwide.",
    expertiseTitle: "Expertise & Advice",
    expertiseDescription: "Our team of passionate experts guides you in choosing products perfectly suited to your specific needs.",
    customerServiceTitle: "Exceptional Customer Service",
    customerServiceDescription: "We are committed to providing a pleasant shopping experience and responsive, efficient after-sales service.",
    joinUsTitle: "Join the Penventory Community",
    joinUsDescription: "Discover our selection of exceptional products and join thousands of satisfied customers who trust Penventory for their stationery and office supply needs.",
    exploreProducts: "Explore our products",
    
    // Page Wishlist
    myWishlist: "My Wishlist",
    emptyWishlist: "Your wishlist is empty",
    emptyWishlistMessage: "You haven't added any products to your wishlist yet. Browse our catalog and add your favorite products!",
    continueShopping: "Continue Shopping",
    clearWishlist: "Clear List",
    confirmClearWishlist: "Are you sure you want to clear your wishlist?",
    wishlistCleared: "Your wishlist has been cleared",
    wishlistItemRemoved: "Product removed from wishlist",
    wishlistLoadError: "Error loading wishlist",
    wishlistRemoveError: "Error removing product",
    addedToCart: "Product added to cart",
    addToCartError: "Error adding to cart",
    removeFromWishlist: "Remove from list",
    product: "Product",
    price: "Price",
    status: "Status",
    actions: "Actions",
    item: "item",
    items: "items",
    inStock: "In stock",
    outOfStock: "Out of stock",
    priceUnavailable: "Price unavailable",
    viewCart: "View Cart",
    currency: "Dt",
  }
};

// Création du contexte
const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  // Récupérer la langue préférée du navigateur ou utiliser le français par défaut
  const [language, setLanguage] = useState('fr');
  
  // Charger la langue depuis le localStorage au démarrage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);
  
  // Sauvegarder la langue dans le localStorage à chaque changement
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);
  
  // Fonction pour changer de langue
  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };
  
  // Fonction pour traduire une clé
  const t = (key) => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Hook personnalisé pour utiliser le contexte de langue
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
